### PR TITLE
Deferred Deep Links

### LINKED ISSUE #154: Deep links and deferred deep links from Facebook ads
Would it be possible to catch deep links from Facebook ads using this plugin like at the below link?

https://developers.facebook.com/docs/app-ads/deep-linking/#deferred-deep-linking

Would really appreciate some input on that since I can't find any resources regarding FB deep links in Nativescript.

Thanks!

### PR DESCRIPTION
**Pull request by alexgritton**
This adds deferred deep links and deep links to the plugin.  I also updated the readme to add an example. 
Closes #154

### CODE REVIEW

**Comment by alexgritton** [comment]
@cla-bot check

**Comment by alexgritton** [comment]
@cla-bot check

**Review by NathanWalker — APPROVED** [review]
Thank you @alexgritton

**Comment by NathanWalker** [comment]
We can update it to {N} 7 after merge.

**Pull request merged**
